AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/ExplicitBlockArgument:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Naming/BlockForwarding:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
